name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3'
          - '3.4'

    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231 # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@97ecb7b512899eb71ab1bf2310a624c6f1589ac6 # v1.308.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run specs
        env:
          COVERAGE: 'true'
        run: bundle exec rspec

      - name: Upload coverage to Codecov
        if: matrix.ruby == '3.4' && github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/coverage.xml
          fail_ci_if_error: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231 # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@97ecb7b512899eb71ab1bf2310a624c6f1589ac6 # v1.308.0
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: RuboCop
        run: bundle exec rubocop

      - name: Brakeman
        run: bundle exec brakeman --force --no-pager
